# Generated by Django 2.2.17 on 2021-01-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.CharField(help_text='Optional Display Name', max_length=16, null=True),
        ),
    ]
