# Generated by Django 2.2.17 on 2021-01-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210108_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(help_text='Optional Location', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='biography',
            field=models.TextField(help_text='Optional Biography', max_length=500, null=True),
        ),
    ]
